apiVersion: v1
kind: Service
metadata:
  name: k8s-node-api
  namespace: default
spec:
  type: NodePort
  selector:
    app: k8s-node-api
  ports:
    - port: 3000
      targetPort: 3000
      nodePort: 30001
